"""Lightweight V2 status reconciliation before expensive render dependencies.

This checks confirmed YouTube uploads and whether another render is due.
It uses only Python stdlib plus the small httpx YouTube adapter. It never
creates/upload videos and cannot turn a private video into a public success.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from astra_v2.control import (
    STATE_FILE, REPORT_FILE, due, read_json, state_for_day, utcnow, write_json, IST
)
from astra_v2.youtube import Youtube


def record_verified_video(video_id: str, item: dict, channel_name: str):
    """Update legacy analytics/feed only after public processed status is proven."""
    data = read_json("performance.json")
    videos = data.setdefault("videos", {})
    if not isinstance(videos, dict):
        raise RuntimeError("Performance video history is not a dictionary; refusing update.")
    entry = videos.setdefault(video_id, {})
    if not isinstance(entry, dict):
        raise RuntimeError("Existing video history entry invalid.")
    entry.update({
        "title": item.get("title") or "RAYVAN Original Video",
        "content_id": item.get("content_id") or "",
        "published_at": entry.get("published_at") or utcnow().astimezone(IST).isoformat(),
        "format": item.get("format") or "short",
        "genre": item.get("genre") or "unknown",
        "visibility": "public",
        "channel_key": channel_name,
        "renderer": entry.get("renderer") or "astra-v2",
    })
    write_json("performance.json", data)
    ordered = sorted(
        videos.items(), key=lambda pair: pair[1].get("published_at", "") if isinstance(pair[1], dict) else "",
        reverse=True,
    )
    lines = ["# RAYVAN Video Feed", "",
             "Stories Beyond the Ordinary. Original videos generated by Astra.", ""]
    for vid, row in ordered[:100]:
        if not isinstance(row, dict):
            continue
        title = str(row.get("title") or "YouTube video").replace("\n", " ").replace("[", "(").replace("]", ")")
        date = str(row.get("published_at") or "")[:10]
        lines.append("- [" + title + "](https://www.youtube.com/watch?v=" + vid + ") · " + date)
    Path("SHORTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def reconcile_pending(youtube: Youtube, state: dict, channel_name: str):
    confirmed = []
    in_process = []
    needs_review = []
    for video_id, entry in list(state.get("pending", {}).items()):
        status = youtube.status(video_id)
        privacy = status.get("privacyStatus")
        upload_status = status.get("uploadStatus")
        if privacy == "public" and upload_status == "processed":
            record_verified_video(video_id, entry, channel_name)
            cid = str(entry.get("content_id") or "")
            state.setdefault("published", {})[cid] = {
                "video_id": video_id,
                "confirmed_at": utcnow().isoformat(),
                "title": entry.get("title") or "",
            }
            if entry.get("day") == state.get("day"):
                state["confirmed_today"] = int(state.get("confirmed_today", 0)) + 1
            del state["pending"][video_id]
            confirmed.append(video_id)
        elif upload_status in {"failed", "rejected", "deleted"} or privacy == "private":
            state.setdefault("needs_review", {})[video_id] = {
                "reason": "youtube_nonpublic_or_failed",
                "observed_at": utcnow().isoformat(),
                "upload_status": upload_status or "unknown",
            }
            del state["pending"][video_id]
            needs_review.append(video_id)
        else:
            in_process.append(video_id)
    return confirmed, in_process, needs_review


def main():
    state = state_for_day(read_json(STATE_FILE))
    report = {
        "at": utcnow().isoformat(),
        "outcome": "preflight",
        "channel": os.getenv("ASTRA_CHANNEL", "rayvan"),
        "video_url": None,
    }
    try:
        from astra_v2.run import channel_config
        channel_name, expected_id = channel_config()
        report["channel"] = channel_name
        if state.get("pending"):
            with Youtube(expected_id) as youtube:
                youtube.authorize()  # validates exact authorized channel
                confirmed, pending, review = reconcile_pending(youtube, state, channel_name)
            report.update(
                confirmed_prior=confirmed,
                pending_video_ids=pending,
                needs_review=review,
            )
        limit = min(100, max(1, int(os.getenv("ASTRA_MAX_DAILY_UPLOADS", "100"))))
        interval = max(14, int(os.getenv("ASTRA_MIN_UPLOAD_INTERVAL_MINUTES", "14")))
        allowed, reason = due(state, utcnow(), limit=limit, spacing_minutes=interval)
        report["render_due"] = allowed
        report["reason"] = reason
        if report.get("confirmed_prior"):
            report["outcome"] = "published"
            report["video_url"] = "https://www.youtube.com/watch?v=" + report["confirmed_prior"][-1]
        elif report.get("needs_review"):
            report["outcome"] = "needs_review"
        elif report.get("pending_video_ids"):
            report["outcome"] = "processing"
        else:
            report["outcome"] = "ready" if allowed else "skipped"
        state["last_outcome"] = report["outcome"]
        return report
    except Exception as exc:
        report.update(outcome="failure", reason=type(exc).__name__ + ": " + str(exc)[:150])
        state["last_error"] = str(exc)[:300]
        state["last_outcome"] = "failure"
        raise
    finally:
        report.update(attempts_today=state["attempts"], confirmed_today=state["confirmed_today"],
                      pending=len(state["pending"]), blocked_until=state.get("blocked_until") or None)
        write_json(STATE_FILE, state)
        write_json(REPORT_FILE, report)
        output = os.environ.get("GITHUB_OUTPUT")
        if output:
            with open(output, "a", encoding="utf-8") as handle:
                handle.write("render_due=" + str(bool(report.get("render_due"))).lower() + "\n")
        print("ASTRA_V2_PREFLIGHT=" + json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
